import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Sidebar from "@/components/Sidebar";
import { AppInteractionShell } from "@/components/interactions/AppInteractionShell";
import { ThemeProvider } from "@/components/ThemeProvider";
import { MobileHeader } from "@/components/MobileHeader";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="flex h-full bg-background text-foreground overflow-hidden transition-colors duration-300">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <div className="flex h-full w-full flex-col lg:flex-row overflow-hidden">
            <MobileHeader />
            <Sidebar />
            <main className="flex-1 flex flex-col overflow-hidden relative">
              {children}
            </main>
          </div>
          <AppInteractionShell />
        </ThemeProvider>
      </body>
    </html>
  );
}
